Update setup.py
Need to add wheel to requires.
    
WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: /home/bilal/PycharmProjects/ehlc_web/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-162i7_40/setuptools-hg/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-162i7_40/setuptools-hg/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-bellpgql
           cwd: /tmp/pip-wheel-162i7_40/setuptools-hg/
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
    
      error: invalid command 'bdist_wheel'